version: "3.9"

services:
  db:
    image: postgres:9.6-bullseye
    volumes:
      - ./temp/data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_NAME: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
