#+title: dqt - Data Quality Tool

A simple data quality tool. Collect and publish metrics about quality of data anywhere.

* Docs

1. [[./docs/dimensions.org][Dimensions of data quality]]

* Features [0/10]

- [ ] publish metrics to aws
- [ ] publish metrics to prometheus
- [ ] publish metadata to DataHub
- [ ] build dashboards
- [ ] alets based on CloudWatch
- [ ] other cloud providers?
- [ ] multiple data sources
- [ ] example dag with airflow
- [ ] example with prefect


* Installation

Download from https://github.com/warfox/dqt

* Usage

FIXME: explanation

Run the project directly, via `:exec-fn`:

#+begin_src
    $ clojure -X:run-x
    Hello, Clojure!
#+end_src

Run the project, overriding the name to be greeted:

#+begin_src
    $ clojure -X:run-x :name '"Someone"'
    Hello, Someone!
#+end_src

Run the project directly, via `:main-opts` (`-m dqt.core`):

#+begin_src
    $ clojure -M:run-m
    Hello, World!
#+end_src

Run the project, overriding the name to be greeted:

#+begin_src
    $ clojure -M:run-m Via-Main
    Hello, Via-Main!
#+end_src

Run the project's tests (they'll fail until you edit them):

#+begin_src
    $ clojure -T:build test
#+end_src


Run the project's CI pipeline and build an uberjar (this will fail until you edit the tests to pass):

#+begin_src
    $ clojure -T:build ci
#+end_src


This will produce an updated =pom.xml= file with synchronized dependencies inside the =META-INF=
directory inside =target/classes= and the uberjar in =target=. You can update the version (and SCM tag)
information in generated =pom.xml= by updating =build.clj=.

If you don't want the =pom.xml= file in your project, you can remove it. The =ci= task will
still generate a minimal =pom.xml= as part of the =uber= task, unless you remove =version=
from =build.clj=.

Run that uberjar:

#+begin_src
    $ java -jar target/dqt-0.1.0-SNAPSHOT.jar
#+end_src


If you remove =version= from =build.clj=, the uberjar will become =target/dqt-standalone.jar=.

* Options

FIXME: listing of options this app accepts.

* Examples

...


* License

Copyright © 2021 Warfox

Distributed under the MIT License.
