name: Build

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:9.6-bullseye
        env:
          POSTGRES_NAME: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@3.7
        with:
          cli: 1.10.3.1040

      - name: Test on Linux and MacOS
        if: ${{ matrix.os != 'windows-latest' }}
        run: clojure -T:build test
        shell: bash

      - name: Test on Windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: clojure -T:build test
        shell: powershell

      - name: Uberjar on Linux and MacOS
        if: ${{ matrix.os != 'windows-latest' }}
        run: clojure -T:build uberjar
        shell: bash

      - name: Uberjar on Windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: clojure -T:build uberjar
        shell: powershell
