name: Build

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:9.6-bullseye
        env:
          POSTGRES_NAME: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@3.7
        with:
          cli: 1.10.3.1040

      - name: Test
        run: clojure -T:build test
        shell: bash
        env:
          DATABASE_HOSTNAME: localhost

      - name: Uberjar
        run: clojure -T:build uberjar
        shell: bash
