name: clj-kondo checks

on: [push]

jobs:
  self-lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: DeLaGuardo/clojure-lint-action@master
      with:
        clj-kondo-args: --parallel --lint src tests
        github_token: ${{ secrets.GITHUB_TOKEN }}
