name: Test

on:
  push:
    paths-ignore:
    - 'docs/**'

jobs:

  test:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:9.6-bullseye
        env:
          POSTGRES_NAME: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'
          cache: maven

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@7.0
        with:
          cli: 1.11.1.1113

      - name: cljfmt-check
        run: clojure -M:format/cljfmt-check

      - name: Test
        run: ./bin/kaocha
        shell: bash
        env:
          DATABASE_HOSTNAME: localhost
